baseURL = "http://ileopold.cn/"
languageCode = "zh-cn"
title = "Headbanger"
theme = "yinyang"
DefaultContentLanguage = "cn"
enableRobotsTXT = true
canonifyURLs = false
refLinksErrorLevel = "WARNING"
refLinksNotFoundURL = "/404"

# [related]
# includeNewer = true
# threshold = 80
# toLower = false
# [[related.indices]]
# name = "date"
# weight = 100
# [[related.indices]]
# name = "keywords"
# weight = 100

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = true
    lineNumbersInTable = true
    style = "rrt" #https://xyproto.github.io/splash/docs/
    tabWidth = 2

[author]
  name = "ileopold"
  homepage = "http://ileopold.cn/"

[languages]
#   [languages.en]
#     contentDir = "content/en"
#     languageName = "English"
#     weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "简体中文"
    weight = 2

[permalinks]
    post = "/blog/:title/"

[params]
headTitle = "Headbanger"
description = "For self tracking and make progress"
favicon = "/logo.png"
mainSections = ["posts"]
staticPrefix = "https://cdn.jsdelivr.net/gh/biexiang/headbanger@main/static"
postHeaderContent = ""
# postFooterContent = '<br/><a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons License" style="border-width:0" src="http://ileopold.cn/images/cc.png" /></a>'
disqus = "ileopold" 
lazyImage = true
googleAnalyticsID = "G-JV86B54BT8" # https://gist.github.com/zjeaton/42246742cdaf2fb46400d04c2eba9a8a

# extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-53624533-8"></script><script src="https://cdn.jsdelivr.net/gh/joway/homepage/analytics.js"></script>'
# extraBody = '<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>'
# postAds = '<ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-6400651395935595" data-ad-slot="5705651853" data-ad-format="auto" data-full-width-responsive="true"></ins>'

[[params.socials]]
name = "Game"
link = "https://steamcommunity.com/id/ileopold0524/games/?tab=all"

[[params.socials]]
name = "Movie"
link = "https://movie.douban.com/people/ileopold/collect"

[[params.socials]]
name = "Book"
link = "https://book.douban.com/people/ileopold/collect"

[[params.socials]]
name = "Travel"
link = "/categories/travel/"

[[params.socials]]
name = "About"
link = "/about"


