baseURL = "https://blog.ileopold.cn/"
languageCode = "en-us"
title = "Headbanger"
theme = "yinyang"
DefaultContentLanguage = "cn"
enableRobotsTXT = true
canonifyURLs = false

# [related]
# includeNewer = true
# threshold = 80
# toLower = false
# [[related.indices]]
# name = "date"
# weight = 100
# [[related.indices]]
# name = "keywords"
# weight = 100

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    # style = "tango"
    tabWidth = 2

[author]
  name = "ileopold"
  homepage = "https://ileopold.cn/"

[languages]
#   [languages.en]
#     contentDir = "content/en"
#     languageName = "English"
#     weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "简体中文"
    weight = 2

[permalinks]
    post = "/blog/:title/"

[params]
headTitle = "Headbanger"
description = "Self Tracking & Make Fun"
favicon = "/logo.png"
mainSections = ["posts"]
# staticPrefix = "https://cdn.jsdelivr.net/gh/joway/blog"
postHeaderContent = ""
postFooterContent = '<br/><br/><p>Subscribe：<a target="_blank" href="https://mailchi.mp/a1a0d59e7a19/joway"><b>Mailchimp</b></a></p><br/><a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://blog.joway.io/images/cc.png" /></a>'
disqus = "ileopold" # disqus account name
lazyImage = true
# extraHead = '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-53624533-8"></script><script src="https://cdn.jsdelivr.net/gh/joway/homepage/analytics.js"></script>'
# extraBody = '<script>(adsbygoogle = window.adsbygoogle || []).push({});</script>'
# postAds = '<ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-6400651395935595" data-ad-slot="5705651853" data-ad-format="auto" data-full-width-responsive="true"></ins>'

[[params.socials]]
name = "Game"
link = "https://steamcommunity.com/id/ileopold0524/games/?tab=all"

[[params.socials]]
name = "Movie"
link = "https://movie.douban.com/people/ileopold/collect"

[[params.socials]]
name = "Book"
link = "https://book.douban.com/people/ileopold/collect"

[[params.socials]]
name = "Travel"
link = "/categories/travel/"

[[params.socials]]
name = "About"
link = "/about"


