name: 'Trigger to update blog'
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'ssh remote rebuild'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SECRET }}
          script: cd /home/ileopold/application/headbanger && git pull && git submodule update --recursive